# Numpy

In [1]:
import numpy as np 

In [2]:
vector_arr = np.array([10,20,30])
vector_arr.ndim #n dimension

1

In [3]:
vector_arr2 = np.array([50,60,70])

toplam = vector_arr + vector_arr2
toplam

array([ 60,  80, 100])

In [4]:
matrix_arr = np.array(
    [
        [10,20,30],
        [30,40,50]
    ]
)
matrix_arr.ndim

2

In [5]:
matrix_arr2 = np.array(
    [
        [60,70,80],
        [90,100,110]
    ]
)
matrix_arr2.shape

(2, 3)

In [11]:
matrix_arr3 = np.array(
    [
        [10,20],
        [30,40],
        [50,60]
    ]
)

toplam = matrix_arr2 + matrix_arr3.reshape(2,3) # (3,2) yerine (2,3) yaptık
toplam

array([[ 70,  90, 110],
       [130, 150, 170]])

In [12]:
carpim = matrix_arr2 * matrix_arr3.reshape(2,3) # Bu dot product değil düz değerleri çarpma
carpim

array([[ 600, 1400, 2400],
       [3600, 5000, 6600]])

In [7]:
np.dot(matrix_arr2,matrix_arr3)

array([[ 6700,  8800],
       [ 9400, 12400]])

# Tensor

In [14]:
tensor1 = np.array(
    [
        [[10,20],[30,40],[50,60]],
        [[70,80],[90,100],[110,120]],
        [[130,140],[150,160],[170,180]],
        [[190,200],[210,220],[230,240]]
    ]
)
tensor1.size, tensor1.ndim, tensor1.shape

(24, 3, (4, 3, 2))

In [18]:
tensor2 = np.random.randint(0,256,(100,100,3))
tensor2

array([[[181, 138,  66],
        [ 38, 100, 103],
        [193,  56,  11],
        ...,
        [ 33,  16, 127],
        [ 13, 124,  39],
        [246,  71,  76]],

       [[ 31, 249, 158],
        [ 40, 108,   3],
        [114, 111, 247],
        ...,
        [249, 157,  32],
        [207,  70, 201],
        [  4,  35, 214]],

       [[ 12, 160, 219],
        [175,   5,  86],
        [229,  76,  53],
        ...,
        [220, 129, 204],
        [165, 203,  23],
        [ 84,  41,  38]],

       ...,

       [[144,  74, 202],
        [ 29, 222,  58],
        [108, 190, 231],
        ...,
        [137, 133, 213],
        [ 95, 131,  26],
        [103, 171, 235]],

       [[  5, 102,  52],
        [251, 169,  67],
        [ 84, 246, 190],
        ...,
        [197, 152, 183],
        [115,  38, 142],
        [ 95,  51, 214]],

       [[  9,   9, 196],
        [ 53, 251,   4],
        [ 17, 162, 150],
        ...,
        [100, 111, 249],
        [ 42, 116,  98],
        [106,  22,  63]]

In [21]:
from PIL import Image
image = Image.open("kedi.jpg")
image_array = np.array(image)
image_array.shape

ModuleNotFoundError: No module named 'PIL'